---
# ------------------------------------------------------------------------------
# Ref:
#   https://jekyllrb.com/docs/configuration/front-matter-defaults/
# ------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    
host: 192.168.1.248

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

sass:
    sass_dir: '_sass'
...
